name: Make index.md from CHANGELOG

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  make-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure changelog exists
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "CHANGELOG.md not found. Aborting." >&2
            exit 1
          fi

      - name: Sync to index.md
        run: |
          if [ -f CHANGELOG.md ]; then
            cp CHANGELOG.md index.md
          fi

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(pages): update index.md from CHANGELOG.md"
          file_pattern: index.md
